# Generated by Django 2.0.5 on 2018-09-26 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20180925_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.Classification', verbose_name='个人博客文章分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'javascript'), (3, 'openstacks'), (4, 'linux'), (5, 'php')], default=None, verbose_name='文章类型'),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读次数'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.ImageField(upload_to='static/upload/photo', verbose_name='图片'),
        ),
    ]
