# Generated by Django 2.0.5 on 2018-09-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_remove_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(null=True, upload_to='static/upload/artcle', verbose_name='文章封面'),
        ),
    ]
