# Generated by Django 2.0.5 on 2018-09-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='suffix',
            field=models.CharField(max_length=32, unique=True, verbose_name='主站名称'),
        ),
    ]
