# Generated by Django 2.0.5 on 2018-10-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_trouble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trouble',
            name='ptime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
