# Generated by Django 2.0.5 on 2018-10-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_auto_20181003_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.IntegerField(choices=[(0, '未发布'), (1, '已发布')], default=0),
        ),
    ]
