# Generated by Django 2.0.5 on 2018-10-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_auto_20181003_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroubleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('context', models.TextField()),
            ],
            options={
                'verbose_name_plural': '报障单模板',
            },
        ),
        migrations.AlterModelOptions(
            name='trouble',
            options={'verbose_name_plural': '报障单'},
        ),
    ]
