# Generated by Django 2.0.5 on 2018-10-03 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20181003_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubletemplate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.UserInfo'),
            preserve_default=False,
        ),
    ]
