# Generated by Django 2.0.5 on 2018-10-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_auto_20181003_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trouble',
            name='evaluate',
            field=models.IntegerField(blank=True, choices=[(1, '不满意'), (2, '一般'), (3, '活很好')], null=True),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
