# Generated by Django 2.0.5 on 2018-10-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0020_action_menu_permission_permissiontoaction_role_roletopremissiontoaction_userinfotorole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=128),
        ),
    ]
