# Generated by Django 2.0.5 on 2018-10-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0021_auto_20181006_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(default='warm', max_length=32, verbose_name='博客主题'),
        ),
    ]
