# Generated by Django 2.0.5 on 2018-10-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0022_auto_20181006_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论次数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='down_count',
            field=models.IntegerField(default=0, verbose_name='踩次数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_count',
            field=models.IntegerField(default=0, verbose_name='点赞次数'),
        ),
    ]
